# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Create 3 differents Series, each of length 100, as follows:
1. The first a random number from 1 to 4
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [2]:
first = pd.Series(np.random.randint(1,5,100))
second = pd.Series(np.random.randint(1,3,100))
third = pd.Series(np.random.randint(10000,30000,100))

### Step 3. Let's create a DataFrame by joinning the Series by column

In [3]:
housemkt = pd.concat([first,second,third],axis=1)
housemkt.head()

   0  1      2
0  1  2  17807
1  4  2  12221
2  2  2  17848
3  3  2  20580
4  1  1  23627

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [5]:
housemkt.rename(columns={0:'beds', 1:'baths', 2:'price_sqr_meter'}, inplace=True)
housemkt.head()

   beds  baths  price_sqr_meter
0     1      2            17807
1     4      2            12221
2     2      2            17848
3     3      2            20580
4     1      1            23627

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [8]:
bigcolumn = pd.concat([first,second,third],axis=0)
bigcolumn.to_frame()
bigcolumn.shape

(300,)

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [10]:
len(bigcolumn)
bigcolumn.tail()

95    28006
96    13226
97    25435
98    20639
99    20802
dtype: int64

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [11]:
bigcolumn.reset_index(drop=True, inplace=True)
bigcolumn.tail()

295    28006
296    13226
297    25435
298    20639
299    20802
dtype: int64